### ISSUE TITLE
Chat spam "XX already is the Your Character Collection."

### ISSUE THREAD

**Issue by GunB** [PayneZA/OutfitManager#3]
Everytime I change maps or do anything, the chat gets a notification with "XX already is the Your Character Collection.". Is there a way to supress these notifications? I enabled the options to keep the glamourer/collection among instances and gearsets. Would like it to not spam my chat with something I decided to do.

**Comment by PayneZA** [comment]
Other than disabling the "Re-wear" outfits option, unfortunately not, as that message comes from penumbra which doesn't have a option to suppress them. The "Re-wear" option is basically the same as using the wear command on a outfit whenever you change instance and since the outfit manager does not know what collection you currently have active it can't go "Oh this collection is already active, I won't try re-apply".

90% of the time chances are the collection hasn't been changed so I added an option for collection to not be re-applied on re-wear. Update should be soon (within 24 hours) so enabling that would solve the problem, 

If you do change collection to something else though then the glam will not look correct so it will be off by default.
