### ISSUE TITLE
Feature Request: Add ability to create penumbra collections.

### ISSUE THREAD

**Issue by indus42** [PayneZA/OutfitManager#8]
Add a button to create and switch to a penumbra collection next to where you type in the collection name.
Additionally a new setting option to auto add a inherited collection to the newly created collection.

Some extra buttons to quick open the related plugins would be great as well.

**Comment by indus42** [comment]
Likewise a button to create a new glamourer design would be great.
Ie: Type in the name in outfit manager click then "Create and Switch".

**Comment by PayneZA** [comment]
Regarding the Collection Addition, 
That's not a feature I'd add since people use collections different ways and the correct intended way for penumbra is making use of inheritance which that wouldn't cater for, penumbra is simply better at this than doing a copy of everything you currently using. 

The Glamourer Design
This is something I'd love to be able to do but unfortunately glamourer doesn't allow for this, a new glamourer is also coming and however it changes will alter what I can do.

**Comment by indus42** [comment]
For Penumbra perhaps I didn't explain properly? I'm not looking to copy the enabled mods to a new collection, but simply to add an inherited collection to the newly created one automatically.
In my use case I have the collections: Fem Miqo -> [Outfit]. 
So my workflow for a new outfit is create a new collection set the inheritance to Fem Miqo, then enable the clothing mods Equip and save Glamourer equipment only then type everything into OutfitManager.

I'm not sure if Penumbra has the API for it, but if it does it'd be great if at least collection creation and inheritance could be done from OutfitManager.

**Comment by PayneZA** [comment]
You basically use it exactly as I do.

There is a feature already to enable in /omg config for if you leave the penumbra collection box empty it will use the one you are currently have applied in either yourself or individual (depending on what its setup for)

Glamourer support was there briefly but only in the form of outfitmanger saving the design in its own config instead of glamourer saving it in theirs,  but with Glamourer 2, if its not supported then there would be a bunch of people whose outfits no longer work.

Penumbra support basically exists as much as it can and when the new Glamourer comes out I'll definitely add an "auto design create" if its possible.

Hope that answers your questions.

Hope that answers your questions
