### ISSUE TITLE
Outfitmanger Crashing with newest Update on Glamourer

### ISSUE THREAD

**Issue by nerikotatsunagi** [PayneZA/OutfitManager#9]
When applying a new glamourer state, somehow the glamourer plugin is interfering and i can't pinpoint the issue in there. At least it is persistent and you can use the game still, but Dalamud itself consinders the game as being crashed, opening the crash window. But you can still play the game (and change outfits afterwards)

[dalamud_appcrash_20230926_200048_436_22588.log](https://github.com/PayneZA/OutfitManager/files/12730635/dalamud_appcrash_20230926_200048_436_22588.log)

**Comment by PayneZA** [comment]
If this is happening in v0.0.6.2 of outfit manager then it might have to be a disable and wait for now unfortunately since the first bug I encountered I could reproduce but this one I cant. I had the problem with versions before that.

Glamourer is going through fixes right now so I don't know whether its outfit manager, glamourer, both, so it's going to take a bit, what with being busy with normal work as well.

Sorry for the inconvenience but I'm working on it as much as I can right now.

**Comment by PayneZA** [comment]
Ok I got the problem after glamourer update to 1.0.1, have done another update v0.0.6.3 and its not crashing my dalamud now however I had to remove the "equip gearset then glamourer design" delay, so its best effort there.

Please let me know how it goes for you.

**Comment by nerikotatsunagi** [comment]
Works like a charm! And no worries. I did not wanted to nitpick or anything, but it was just a: Oh, sth is not going the way it should be, better inform you and have you check on it (as i am not a coder)
